[package]
name = "particles"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytemuck = "1"
futures = "0.3"
wgpu = "0.19"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
flume = "0.11.0"
